# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [122]:
import torch

In [123]:
print(torch.__version__)

2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
torch.arange(0, 10, 1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [125]:
tensor = torch.arange(0, 10, 1)
vector_tensor = tensor
print(
    f"Какого типа элементы вектора   --> {tensor.dtype}",
    f"Размеры вектора                --> {tensor.shape}",
    f"Количество размерностей        --> {tensor.dim()}",
    sep="\n\n",
)


Какого типа элементы вектора   --> torch.int64

Размеры вектора                --> torch.Size([10])

Количество размерностей        --> 1


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [126]:
tensor1 = tensor[:5]
tensor2 = tensor[5:10]
print(tensor1, tensor2)

tensor([0, 1, 2, 3, 4]) tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [127]:
torch.ones(3, 4, dtype=torch.double)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [128]:
torch.ones(2, 5, dtype=torch.bool)


tensor([[True, True, True, True, True],
        [True, True, True, True, True]])

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [129]:
torch.arange(1, 16, 0.5, dtype=torch.double)


tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000],
       dtype=torch.float64)

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [130]:
torch.linspace(1, 11, 20, dtype=torch.float16)


tensor([ 1.0000,  1.5264,  2.0527,  2.5781,  3.1055,  3.6328,  4.1562,  4.6836,
         5.2109,  5.7383,  6.2617,  6.7891,  7.3164,  7.8438,  8.3672,  8.8906,
         9.4219,  9.9453, 10.4766, 11.0000], dtype=torch.float16)

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [131]:
torch.rand(4, 3, dtype=torch.float32)

tensor([[5.0475e-01, 6.0433e-02, 6.4892e-04],
        [4.9306e-01, 5.6962e-01, 7.7946e-01],
        [6.0436e-02, 1.3155e-01, 2.7949e-02],
        [5.5396e-01, 2.7156e-01, 7.2090e-01]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [132]:
tensor3 = torch.randint(3, 6, (1, 100), dtype=torch.float32)
print(tensor3)

tensor([[3., 3., 3., 5., 4., 5., 5., 4., 4., 4., 3., 3., 5., 4., 4., 5., 4., 3.,
         5., 5., 3., 4., 3., 5., 5., 4., 3., 4., 3., 4., 4., 5., 3., 3., 3., 4.,
         5., 5., 5., 5., 4., 5., 5., 3., 5., 3., 5., 4., 5., 4., 4., 4., 4., 3.,
         4., 3., 3., 3., 5., 3., 5., 3., 5., 3., 5., 3., 3., 5., 4., 5., 5., 5.,
         4., 3., 3., 5., 4., 5., 4., 3., 5., 4., 4., 5., 4., 4., 3., 3., 5., 4.,
         5., 3., 3., 5., 3., 5., 4., 5., 5., 3.]])


Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [133]:
vector_tensor = tensor3
print(
    f"Максимальное значение:\n{vector_tensor.max()}",
    f"Минимальное значение:\n{vector_tensor.min()}",
    f"Среднее арифметическое элементов:\n{vector_tensor.mean()}",
    sep="\n\n",
)


Максимальное значение:
5.0

Минимальное значение:
3.0

Среднее арифметическое элементов:
4.039999961853027


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [134]:
bool_mask_1 = torch.tensor([True]*5 + [False]*90 + [True]*5)
tensor4 = tensor3 * bool_mask_1
print(tensor4)

tensor([[3., 3., 3., 5., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 5., 4., 5., 5., 3.]])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [135]:
tensor = tensor4
mask = tensor4 != 0
tensor5 = torch.masked_select(tensor, mask)
print(tensor5)

tensor([3., 3., 3., 5., 4., 5., 4., 5., 5., 3.])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [136]:
bool_mask = tensor5 == 5.0
print(bool_mask)

tensor([False, False, False,  True, False,  True, False,  True,  True, False])


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [137]:
tensor6 = tensor5[tensor5 == 5.0]
print(tensor6)


tensor([5., 5., 5., 5.])


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [138]:
tensor7 = tensor3.reshape(5, 20)
print(tensor7)

tensor([[3., 3., 3., 5., 4., 5., 5., 4., 4., 4., 3., 3., 5., 4., 4., 5., 4., 3.,
         5., 5.],
        [3., 4., 3., 5., 5., 4., 3., 4., 3., 4., 4., 5., 3., 3., 3., 4., 5., 5.,
         5., 5.],
        [4., 5., 5., 3., 5., 3., 5., 4., 5., 4., 4., 4., 4., 3., 4., 3., 3., 3.,
         5., 3.],
        [5., 3., 5., 3., 5., 3., 3., 5., 4., 5., 5., 5., 4., 3., 3., 5., 4., 5.,
         4., 3.],
        [5., 4., 4., 5., 4., 4., 3., 3., 5., 4., 5., 3., 3., 5., 3., 5., 4., 5.,
         5., 3.]])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [139]:
# В задании ошибка, нет функции torch.repeat.
# Думаю, можно заполнить тензор любыми элементами (например единицами) и просто состыковать любые 2 тензора

a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)
c = torch.zeros(2, 5)
c[:, :2] = a
d = b.view(2, 5)

result = torch.cat([c, d])
print(result)

tensor([[2., 4., 0., 0., 0.],
        [6., 8., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [140]:
# Здесь встречается та же опечатка с repeat
# repeat заменена на ones
a = torch.arange(2, 10, 2).reshape(2, -1)
b = torch.ones(10).reshape(2, -1)
tensor8 = torch.cat([a, b], dim=1)
print(tensor8)

tensor([[2., 4., 1., 1., 1., 1., 1.],
        [6., 8., 1., 1., 1., 1., 1.]])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [141]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
tensor9 = a[(a >= 5) & (a <= 10)]
print(tensor9)

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [142]:
print(tensor8[0])

tensor([2., 4., 1., 1., 1., 1., 1.])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [143]:
print(result)
print(result[:, 4])

tensor([[2., 4., 0., 0., 0.],
        [6., 8., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([0., 0., 1., 1.])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [144]:
print(result[1:3, 1:4])

tensor([[8., 0., 0.],
        [1., 1., 1.]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [145]:
min_element = result.min()
new_row = torch.full((1, result.shape[1]), min_element)
tensor10 = torch.cat([new_row, result], dim=0)

print(tensor10)

tensor([[0., 0., 0., 0., 0.],
        [2., 4., 0., 0., 0.],
        [6., 8., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [146]:
result_sqrt = tensor10.sqrt()
print(result_sqrt)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.4142, 2.0000, 0.0000, 0.0000, 0.0000],
        [2.4495, 2.8284, 0.0000, 0.0000, 0.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [147]:
mask = (tensor8 % 2 == 0) | (tensor8 % 3 == 0)
tensor11 = tensor8.clone()
tensor11[mask] = 1

print(tensor11)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
